/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoproject;

import algoproject.ChainMatrix;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.io.*;
/**
 *
 * @author Moiz
 */
public class chainMatrixGui extends javax.swing.JFrame {
    ChainMatrix obj;
    /**
     * Creates new form chainMatrixGui
     */
    public chainMatrixGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        filePath = new javax.swing.JTextField();
        nm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pval = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mtable = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        stable = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mincost = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        best = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("No of Matrices:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel9.setText("File path:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 60, 20));

        filePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filePathActionPerformed(evt);
            }
        });
        filePath.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filePathKeyReleased(evt);
            }
        });
        getContentPane().add(filePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 210, -1));
        getContentPane().add(nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 205, -1));

        jLabel2.setText("Values of P:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        pval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pvalActionPerformed(evt);
            }
        });
        getContentPane().add(pval, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 205, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoproject/math-matrix.png"))); // NOI18N
        jLabel3.setText("Chain Matrix Multiplication");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Output");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 166, -1, -1));

        jLabel5.setText("M Table");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 189, -1, -1));
        getContentPane().add(mtable, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 189, 197, 178));

        jLabel7.setText("S Table");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 189, -1, -1));
        getContentPane().add(stable, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 189, 197, 178));

        jButton1.setText("Generate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 89, -1));
        getContentPane().add(mincost, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 19, 89, 88));

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoproject/back-icon.png"))); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 413, -1, -1));

        jLabel6.setText("Best Combination:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 373, -1, -1));
        getContentPane().add(best, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 325, 22));

        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoproject/image.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pvalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pvalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pvalActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
                int n = Integer.parseInt(nm.getText());    
                
                String pval = " ";
                pval=this.pval.getText();
                StringBuilder sbb=new StringBuilder(pval);
                sbb.append(',');
                pval=sbb.toString();
//                System.out.println("1");
                int temp1[] = new int[n+1];
                
                int k=0; //10,20,50
                int last=0;
//                System.out.println("2");
                for(int i=0;i<pval.length();i++){
                    if(pval.charAt(i)==','){     
                        String temp=pval.substring(last, i);
                        temp1[k]=Integer.parseInt(temp);
                        last=i+1;
                        k++; 
                    }
                }
//                System.out.println("3");                
                ChainMatrix obj=new ChainMatrix(n,temp1);
//                System.out.println("4");
                obj.calculate();
//                System.out.println(obj.table1);                
                this.mtable.setText(obj.table1);
                this.stable.setText(obj.table2); 
                this.mincost.setText("<html>Minimum Cost For<br> Current Input is: <br>"+obj.res+"</html>");
                best.setText(obj.printOptimalParens(1, obj.n));
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        mainGUI obj=new mainGUI();
        obj.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void filePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filePathActionPerformed

    private void filePathKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filePathKeyReleased
        // TODO add your handling code here:
        File f = new File(filePath.getText());
        if(f.exists()){
            String fPath=filePath.getText();
            int count=0;

            try (BufferedReader br = new BufferedReader(new FileReader(fPath))) {

                String sCurrentLine;

                while ((sCurrentLine = br.readLine()) != null) {
                    if(count==0){
                        nm.setText(sCurrentLine);
                    }
                    else if (count==1){
                        pval.setText(sCurrentLine);
                    }
                    count++;

                }

            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_filePathKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chainMatrixGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chainMatrixGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chainMatrixGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chainMatrixGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chainMatrixGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel best;
    private javax.swing.JTextField filePath;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mincost;
    private javax.swing.JLabel mtable;
    private javax.swing.JTextField nm;
    private javax.swing.JTextField pval;
    private javax.swing.JLabel stable;
    // End of variables declaration//GEN-END:variables
}
