/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoproject;

/**
 *
 * @author Dell
 */
public class mainGUI extends javax.swing.JFrame {

    /**
     * Creates new form mainGUI
     */
    public mainGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        knapsack = new javax.swing.JButton();
        matrix = new javax.swing.JButton();
        sorting = new javax.swing.JButton();
        datas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(350, 200));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Algo Project - I");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 340, 60));

        knapsack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoproject/binary-icon.png"))); // NOI18N
        knapsack.setText("0/1 Knapsack");
        knapsack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                knapsackActionPerformed(evt);
            }
        });
        getContentPane().add(knapsack, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 170, 40));

        matrix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoproject/math-matrix.png"))); // NOI18N
        matrix.setText("Matrix Multiplication");
        matrix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrixActionPerformed(evt);
            }
        });
        getContentPane().add(matrix, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 170, 40));

        sorting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoproject/sort-ascending-icon.png"))); // NOI18N
        sorting.setText("Sorting Algorithms");
        sorting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortingActionPerformed(evt);
            }
        });
        getContentPane().add(sorting, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 170, 40));

        datas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoproject/Business-Tree-Structure-icon.png"))); // NOI18N
        datas.setText("Data Structures");
        datas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datasActionPerformed(evt);
            }
        });
        getContentPane().add(datas, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 170, 40));

        jPanel1.setLayout(new javax.swing.OverlayLayout(jPanel1));
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 610));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel4.setText("<html>Group Members:<br>Syed Hammad Jaffery (15K-2890)<br>Abdul Moiz Zaveri (15k-2854)<br> Arsalan (15k-2235)");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 300, 110));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoproject/matrix.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void knapsackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_knapsackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        knapsackGUI obj=new knapsackGUI();
        obj.setVisible(true);
    }//GEN-LAST:event_knapsackActionPerformed

    private void sortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortingActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        sortingGui obj=new sortingGui();
        obj.setVisible(true);
    }//GEN-LAST:event_sortingActionPerformed

    private void datasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datasActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        dsGui obj=new dsGui();
        obj.setVisible(true);
    }//GEN-LAST:event_datasActionPerformed

    private void matrixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrixActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        chainMatrixGui obj=new chainMatrixGui();
        obj.setVisible(true);        
    }//GEN-LAST:event_matrixActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton datas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton knapsack;
    private javax.swing.JButton matrix;
    private javax.swing.JButton sorting;
    // End of variables declaration//GEN-END:variables
}
