/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package algoproject;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import java.io.*;
import java.util.LinkedList;
import java.util.Queue;
/**
 *
 * @author Dell
 */
public class radixSortGui extends javax.swing.JFrame {
    int myArray[];
    String iteration;
    String resultt;
    /**
     * Creates new form radixSortGui
     */
    public radixSortGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        array = new javax.swing.JTextField();
        filePath = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        output = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Radix Sort");

        jLabel2.setText("Enter Numbers:");

        filePath.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                filePathKeyReleased(evt);
            }
        });

        jLabel3.setText("File Path:");

        jButton2.setText("Show Iterations");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Sort");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Output: ");

        output.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/algoproject/back-icon.png"))); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(array)
                                    .addComponent(filePath, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(array, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(filePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(output, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void filePathKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filePathKeyReleased
        // TODO add your handling code here:
        File f = new File(filePath.getText());
        if(f.exists()){
            String fPath=filePath.getText();

            try (BufferedReader br = new BufferedReader(new FileReader(fPath))) {

                String sCurrentLine;

                sCurrentLine = br.readLine();
                array.setText(sCurrentLine);

            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_filePathKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(iteration.isEmpty()){
            JOptionPane.showMessageDialog(null, "You didn't sorted the array yet!");
        }else{
            JOptionPane.showMessageDialog(null, iteration);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    private int getMax()
    {
        int max=myArray[0];
        
        for(int i=0;i<myArray.length;i++)
            if(max<myArray[i])
                max=myArray[i];
        
        return max;
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        resultt="";
        iteration="";
        myArray=null;

        String arr=array.getText();
        StringBuilder sb=new StringBuilder(arr);
        sb.append(',');
        arr=sb.toString();
        int last=0;
        int k=0;
        int count=0;

        for(int i=0;i<arr.length();i++){
            if(arr.charAt(i)==','){
                count++;
            }
        }

        myArray=new int[count];

        for(int i=0;i<arr.length();i++){
            if(arr.charAt(i)==','){
                String temp=arr.substring(last, i);
                myArray[k]=Integer.parseInt(temp);
                last=i+1;
                k++;
            }
        }
        StringBuilder s1=new StringBuilder (iteration);
        StringBuilder s2=new StringBuilder (resultt);
        //radix sort code starts here
        int temp,i,j,m;
        int pos,c=0,f=1,max=getMax(),size=myArray.length;
        while(max!=0)    //while loop for getting number of digits of max. number
        {
            max=max/10;
            c++;
        }
        Queue q1[] = new Queue[10];  // making array of Queues containing 10 elements 
        /*
        
        | |  | |  | |  | |  | |  | |  | |  | |  | |  | |  
        |_|  |_|  |_|  |_|  |_|  |_|  |_|  |_|  |_|  |_|
         0    1    2    3    4    5    6    7    8    9  
 
        10 queues for each digit
        */
        for(i = 0; i < 10; i++)   // Array sirf abstract tha abb usmy memory aayi ha
        q1[i] = new LinkedList();         
        
        for(i=1;i<=c;i++)    //C hmara max. number k number of digit ha ... like 1051 ma c ki value 4 hogi tou yeh loop utni baar chalega first for unit then tenth on and on...
        {
            for(j=0;j<size;j++)
            {
                pos=myArray[j]/f;     //harr aik element uthaega aur uska unith(when f=1) , tenth(when f=10) , hundreth(when f=100) digit save krega 'pos' ma
                while(pos>9)
                {
                    pos=pos%10;
                }
                                   
                q1[pos].add(myArray[j]);  //abb pos ma jo number ha ussi index pr jaega Queue myArray ma aur waha pr wo element ko add krega like 541 ka tenth digit '4' ha tou Queue[4] pr 541 ko add krdega
//                    System.out.println(myArray[j]);                
                s1.append(myArray[j]);
                s1.append(',');
            }
//            System.out.println();
            s1.append('\n');
            k=0;
            for(j=0;j<9;j++)   // abb iss loop ma saray queues ko khaali krega line se starting from 0 to 9 aur unkay elements ko original myArray ma daal dega
            {
                while(!q1[j].isEmpty())
                {
                    myArray[k]=(int)q1[j].remove();
                    k++;
                }
            }
            f=f*10;   // f ko multiply by 10 so that next iteration ma tenth position se uthae then usse next hundreth and so onn..
        }
        
       
        
        
        for(i=0;i<size;i++){
//            System.out.print(myArray[i]+" ");
            s2.append(myArray[i]);            
            s2.append(',');            
            s1.append(myArray[i]);            
            s1.append(',');            
        }
        
        iteration=s1.toString();
        resultt=s2.toString();
        output.setText(resultt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        sortingGui obj=new sortingGui();
        obj.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(radixSortGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(radixSortGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(radixSortGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(radixSortGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new radixSortGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField array;
    private javax.swing.JTextField filePath;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel output;
    // End of variables declaration//GEN-END:variables
}
